# Uncomment these lines to add benchmark specific definitions.
# Avoid to change the makefiles in the utilities dir 
#ACCFLAGS=
#ACC_INC_PATH=
#ACC_LIB_PATH=
#ACC_LIBS=
-include ../../utilities/options-nvidia.mk
-include ../../utilities/c.mk