# Uncomment these lines to add benchmark specific definitions.
# Avoid to change the makefiles in the utilities dir 
# CFLAGS=
# INCPATHS=
# LIB_PATH=
LIBS=-lm
-include ../../utilities/options-nvidia.mk
-include ../../utilities/c.mk