# Uncomment these lines to add benchmark specific definitions.
# Avoid to change the makefiles in the utilities dir 
CFLAGS= -I/opt/papi/include/ -DPOLYBENCH_PAPI
# INCPATHS=
LIB_PATH= -L/opt/papi/lib
LIBS= -lpapi
-include ../../utilities/options-nvidia.mk
-include ../../utilities/c.mk